language: node_js

# test on node.js version: 7.10.0
node_js:
  - 7.10.0
install:
  - yarn install
  - yarn build
notifications:
  email: false
  webhooks:
    urls:
    - 'https://webhook.atomist.com/travis'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
